### ISSUE TITLE
How is it now?

### ISSUE THREAD

**Issue by askfiy** [uga-rosa/translate.nvim#1]
This is an interesting plugin that is better than vim-translate because it doesn't require Python dependencies.

I tried to use this plugin, but the documentation is very general. Is it possible to update the README file with the configuration effect and pictures?

I believe doing so will greatly increase the popularity of the plugin.

Also, I found that the plugin has just been developed.

The best translation plugin I've ever used is [comment-translate](https://github.com/intellism/vscode-comment-translate) for vscode, and if this plugin can achieve similar results, then this plugin will be the best translation plugin in neovim world.

Do you have any plans for the follow-up?

**Comment by uga-rosa** [comment]
Hmmm... I thought if you read the help you could set it up, but I guess I should add quick start and gifs to the readme.
I made this plugin for my own use and so far I'm happy with the functionality, but if it can be made better, feature requests and PR are welcome!

**Comment by uga-rosa** [comment]
Do you want a command that automatically selects comment sections using treesitter or highlight?

**Comment by askfiy** [comment]
For people whose native language is not English, it is difficult to read English source code comments. If possible, is it possible to implement the following functions:

1. Use TranslateCommentV or S to open a horizontal or vertical split window

2. Monitor the movement of the cursor, if the cursor is inside the comment area, automatically translate the content of the entire code block to the new window

3. If feasible, can some specific English words not be translated, such as the following xxx and yyy without translation:

- xxx : parameter 1
- yyy : parameter 2

4. Is it possible to provide a highlight color for the Translate and Replace function based on Visual selection

Thank you so much for your reply, I am very happy.

I also want to try to develop some neovim plugins in Lua, but I don't know Viml.

I'm in China and using neovim is not very common in China, so there will be very little information on this.

Thank you again.

**Comment by uga-rosa** [comment]
I intend to design and maintain this plugin as an extensible one. So I will not add the specifications as you wish, but I will add features that will make this possible and will put the configuration instructions on the wiki.

**Comment by askfiy** [comment]
thanks a lot, you can put it in [awesome-neovim](https://github.com/rockerBOO/awesome-neovim)
