### ISSUE TITLE
support translate single word

### ISSUE THREAD

**Issue by Cluas** [uga-rosa/translate.nvim#10]
By convention, I want to call Translate directly to translate the current word, and then Visual Mode to translate multiple lines

**Comment by uga-rosa** [comment]
If you want to translate just one word, a dictionary is fine. I believe that this is not the main target of this plugin, which mainly uses machine translation.
Why not just map `viw:Translate`?

**Comment by Cluas** [comment]
https://github.com/voldikss/coc-translator, I want find something like this. but it's true that `viw:Translate`solved my problem, thanks a lot!

**Comment by uga-rosa** [comment]
The main function of this plugin is to allow the user to freely choose how the translation results are output, etc ;)

**Comment by Cluas** [comment]
> The main function of this plugin is to allow the user to freely choose how the translation results are output, etc ;)

In fact, my main need is to read the comments of some go code, then occasionally there will be words that I don't know the meaning of and want to quickly translate them

**Comment by uga-rosa** [comment]
Well, the mapping I mentioned earlier should be fine. I could add the command TranslateWord, but it is not a priority for me.

**Comment by Cluas** [comment]
> Well, the mapping I mentioned earlier should be fine. I could add the command TranslateWord, but it is not a priority for me.

Overall it works fine now, hope this plugin is getting better and better
