### ISSUE TITLE
Can't `-comment` translate Python docstrings?

### ISSUE THREAD

**Issue by askfiy** [uga-rosa/translate.nvim#13]
Python's docstring is very common.

Below is a screenshot of an open source framework in Python. You can see that most of the source code is comments in docstrings:

![图片](https://user-images.githubusercontent.com/81478335/165094967-9e464632-a312-447e-89ae-37ac2ed9c198.png)

The problem is when using the `-comment` parameter, it prompts me with the following error:

![图片](https://user-images.githubusercontent.com/81478335/165095034-f89309ac-74a5-4f54-9642-283f030ed977.png)

Is there any way we can make it support Python?

docstring format:

```
"""One line"""

'''one line'''

"""
Multi-line
"""

'''
Multi-line
'''
```

**Comment by askfiy** [comment]
Yes, it is indeed very widely used. So looking forward to your results ~ you are awesome!!!

**Comment by uga-rosa** [comment]
Sorry for the delay in responding, I have been busy. I'll work on it this weekend.

**Comment by askfiy** [comment]
ok, looking forward to its completion ..

**Comment by uga-rosa** [comment]
Added. Try it out.

**Comment by askfiy** [comment]
Perfect, Thank you for your efforts
