### ISSUE TITLE
How to translate words under cursor instead of whole line?

### ISSUE THREAD

**Issue by NEX-S** [uga-rosa/translate.nvim#16]
I've found that my translate.nvim will always trans the whole line, if I select the entire paragraph, it still trans the first line. I don't know why this would happen.

This is my keymaps

```lua
vim.keymap.set('n', ';t', ':<C-u>Translate ZH -source=EN -parse_after=window -output=floating<CR>')
vim.keymap.set('v', ';t', ':<C-u>Translate ZH -source=EN -parse_after=window -output=floating<CR>')
vim.keymap.set('x', ';t', ':<C-u>Translate ZH -source=EN -parse_after=window -output=floating<CR>')
```

And this is my translate.nvim config
```
                vim.g.deepl_api_auth_key = '092f0ebb-556b-a1ad-27a9-23e52fbexxxx:fx'
                require "translate".setup {
                    default = {
                        command = "deepl_free",
                    },
                    preset = {
                        output = {
                            split = {
                                append = true,
                            },
                        },
                    },
                }
```

**Comment by uga-rosa** [comment]
Remove `<c-u>` from visual mode mapping. The plugin determines which mode it was called from by looking at [range].

**Comment by NEX-S** [comment]
COOL! Appreciate your reply, have a nice day.

**Comment by NEX-S** [comment]
> Remove `<c-u>` from visual mode mapping. The plugin determines which mode it was called from by looking at [range].

btw, is there any way to map `:Translate` translate words under the cursor becomes the default behavior? I think in most cases we just only need to know the translation of one word.

**Comment by uga-rosa** [comment]
I do this because I want to translate the entire text, but if there is demand, I will provide command `TranslateWord`.

**Comment by uga-rosa** [comment]
In the meantime, mapping `viw:Translate` will do what you want.

**Comment by NEX-S** [comment]
okay <3

**Comment by uga-rosa** [comment]
It is time-consuming to implement TranslateWord as a command because the selection must be known (for use in output, such as replace), and this can be easily solved by mapping, so I decided to add this to README.md.

In addition, \<Cmd> support has been realized. From now on, you can write `<Cmd>Translate ZH<CR>` for both `nmap` and `xmap`.

**Comment by timoleistner** [comment]
I was looking for the same functionality and a simple mapping would be a fine solution.
The problem is if I select anything visually, only the first letter is "translated" and not the whole visual selection.
I am using the minimal configuration with packer:
```Lua
use({
    "uga-rosa/translate.nvim",
    config = function()
        require("translate").setup({})
    end
})
```

**Comment by uga-rosa** [comment]
@timoleistner
I can't reproduce it, so please set up another issue and tell me exactly how to reproduce it.
