### ISSUE TITLE
如果遇到特殊符号开始必须'/'斜线，可以有办法截取掉前面的///吗？

### ISSUE THREAD

**Issue by yil3** [uga-rosa/translate.nvim#17]
有很多代码注释都是/开头，使用的trans这个工具本身就不支持‘/’开始的文本
还有一种方法trans可以在选中文本的前面添加一个空格实现翻译

**Comment by uga-rosa** [comment]
你有没有试过使用-comment标志？

**Comment by yil3** [comment]
@uga-rosa 
看文档没明白，进去看了一下代码也没明白这个选项怎么使用。
config.setup 这个方法并没有和comment相关的内容
command.create_command(M.translate)倒是有了相关内容，没明白实现了什么～
大佬给个完整示例呗！

**Comment by uga-rosa** [comment]
只需在命令中加入-comment作为参数。
以下用途。
```vim
nnoremap mzc <Cmd>Translate ZH -source=EN -comment<CR>
```

**Comment by askfiy** [comment]
@yil3 `translate_shell` now supports C-style comments
