### ISSUE TITLE
Only first letter of visual selection is translated.

### ISSUE THREAD

**Issue by timoleistner** [uga-rosa/translate.nvim#18]
If I select anything visually, only the first letter is "translated" and not the whole visual selection.
I am using the minimal configuration with packer:
```Lua
use({
    "uga-rosa/translate.nvim",
    config = function()
        require("translate").setup({})
    end
})
```
Using the following example
```
Hello, World!
```
If I visually select and translate "Hello" with `viw:Translate de` "Translate success" is printed and the shown translation is "H".
If I visually select and translate "World" the same way, the shown translation is "Im" which doesn't really make sense but if I have a line containing only "W" the translation for this line is also shown as "Im" so the translation is indeed a success just not the visual selection.

**Comment by niuiic** [comment]
Same issue. Roll back to commit `68ead8e98fb85b6364b7a5fc20ca3d6768bc5c37`,  and this should be solved.

**Comment by uga-rosa** [comment]
Thank you for reporting. I’ll look into it.

> Why not use `vim.call('expand',<cWORD>')` for this @uga-rosa ?

This is because this plugin requires a range of text from which to translate, and is used for functions such as output/replace.

**Comment by uga-rosa** [comment]
It should be fixed. Please update to the latest version.

**Comment by uga-rosa** [comment]
Also, this is not directly related, but just to let you know.
If you want to use the default settings, there is no need to call setup.
```lua
use("uga-rosa/translate.nvim")
```
This is all you need to use.

**Comment by timoleistner** [comment]
Can confirm it's fixed! And thanks for the info.
