### ISSUE TITLE
Make non- `-comment` commands also recognize C style comments

### ISSUE THREAD

**Issue by askfiy** [uga-rosa/translate.nvim#19]
Comments starting with `//` are common, but they are currently only translated with `-comment`.

For comments that are not `//` or `/**/` (such as `--` or `#`), can we get the translation result without adding `-comment`.

For example, in the following cases, most people's first instinct is to translate via `-output=floating`, but doing so will fail the translation:

````
// comment

func test() {
    ...
}
````

But in the following cases, `-output=floating` can be successfully recognized and translated:

````
# comment

def test:
    pass
````

My idea is that we can keep `-comment`, but `-output=floating` should also recognize the content of one or more lines starting with `//` or `/*` or ending with `*/`.

Of course, this should not only be limited to `-output=floating`, but should also apply to `-output=split` and other commands without `-comment`.

In normal mode, `-comment` always translates a whole block, but `-output=floating` can translate a line, which is more flexible.

Let `-comment` continue to translate the entire comment. But even without adding `-comment`, the selected content can be translated successfully.

I think it makes sense to unify people's usage habits, so that people can freely choose how they want to annotate translations, rather than having to think about what files I'm editing.

**Comment by uga-rosa** [comment]
Do you mean that you want to automatically add -comment when you call the command in normal mode under the comment? If you implement it, I would like to be able to configure that feature for the user (provide `auto_detect_comment` in setup).

**Comment by askfiy** [comment]
Well, what I described might not be very clear.

In fact, what I mean is that the command without the `-comment` parameter can also be successfully translated in the following situations.

1) Begin with `//`

````
// hello world
````

2) Begin with `/*`

````
/* this is block comment start

hello work

*/
````

Imagine you are a developer who uses many languages like `C` and `Lua`.

There is now one or more lines of `Lua` comments in the `--` or `--[[ ]]` style, and you have successfully obtained your selected area by mapping the keys of `Translate JA -source=EN -output=floating` (since this method of translation is more general, many people will not try to translate by adding `-comment` the first time).

Next, you have a line of `C` language comment that starts with `//` or `/*`, well, you still map keys via the command above for translation.

Unfortunately, you found that it failed to translate, now you need to consider:

- Why did it fail?
- How can I make it work?

For users, they prefer a uniform way to get translation results, regardless of what type of comment style file I'm editing? Which key should I press that I'm bound to? Therefore, I think it is necessary to let the command without adding the `-comment` parameter also get the translation results of the above two cases.

**Comment by uga-rosa** [comment]
Oh I see, I checked with the CLI and the trans command can't translate text that starts with /. This will be fixed.

**Comment by uga-rosa** [comment]
79683628559999911f4b54b1cf095567410f5f7b

**Comment by askfiy** [comment]
I tried it and it works, but it's not perfect.

1) Its translation result will remove the leading `/`.

2) It cannot translate the following format, because `/` is preceded by `\t`:

![image](https://user-images.githubusercontent.com/81478335/184473405-a1e53470-42b2-44ff-a798-a6948b9838e1.png)

I will file a PR later.. it will fix this better.
