### ISSUE TITLE
Translating from cyrillic languages returns question marks

### ISSUE THREAD

**Issue by Goxore** [uga-rosa/translate.nvim#28]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/translate.nvim/discussions).

### Description

Translating from Russian or Ukrainian to any other language returns question marks. Other way around works as expected.

### Environments

Neovim 0.8
Windows 10
Novide or terminal

### Minimal reproducible full config

Default configuration

### Steps to reproduce

Write cyrillic text and translate. No configuration

### Expected behavior

Should return text translated from Russian/Ukrainian

### Actual behavior

Returns question marks

**Comment by uga-rosa** [comment]
Since I am not a Cyrillic speaker, can you provide me with a text that I can use to test the appropriate translation so that I can copy it?

**Comment by Goxore** [comment]
here: 
``Какой-то случайный текст для перевода в текстовом редакторе "Неовим". Написан кириллицей``

for me, it gets translated to this:
``?????-?? ????????? ????? ??? ???????? ? ????????? ????????? "??????". ??????? ??????????``

Expected translation:
``Some random text for translation in the Neovim text editor. Written in Cyrillic``

**Comment by Goxore** [comment]
Sorry I accidentally closed it

**Comment by Goxore** [comment]
I've just tested the same setup on my home Linux machine, and everything works just fine. Maybe the issue is Windows only?

**Comment by uga-rosa** [comment]
I see...I don't assume windows, so maybe that's why. What about &shell?

**Comment by Goxore** [comment]
Tomorrow I won't have access to a Windows computer, so I will try to provide more information later.
I think default shell on that machine is cmd. I'll also try powershell.

**Comment by Goxore** [comment]
Changing cmd to powershell didn't change anything
![image](https://user-images.githubusercontent.com/54540106/199670201-9c836d17-6d0a-4f83-a74d-9124d9949ea3.png)

**Comment by Goxore** [comment]
Yes, and it even converts text to Cyrillic just fine. I have no idea how to fix it, should i close the issue?

**Comment by uga-rosa** [comment]
No, it may take some time, but I will investigate and you can leave it open.
It happens in neovide and in terminal, right?

And, what do you mean?
> Yes, and it even converts text to Cyrillic just fine.

**Comment by Goxore** [comment]
Yes, also tried different fonts

**Comment by uga-rosa** [comment]
I found the cause but it will take some time to solve it. cmd.exe and powershell curl are bad, so I think translate-shell will work properly.

**Comment by uga-rosa** [comment]
Please try.
ddf6900b9045dc661dc367f35aab14622fa47277

**Comment by Goxore** [comment]
Going to tomorrow
