### ISSUE TITLE
Can't translate in visual mode, the result is always blank

### ISSUE THREAD

**Issue by askfiy** [uga-rosa/translate.nvim#3]
It doesn't work in visaul mode, the bottom shows that the translation was successful, but the resulting content is empty.

![Peek 2022-03-09 22-52](https://user-images.githubusercontent.com/81478335/157466304-9c777425-7f63-452f-8972-3983bc457200.gif)

**Comment by uga-rosa** [comment]
What commands and settings are you using?

**Comment by uga-rosa** [comment]
https://github.com/soimort/translate-shell/issues/327
If you are using translate-shell, you may be limited by the google.

**Comment by askfiy** [comment]
> Do you mean that it succeeds in normal mode but does not return results in visual mode?

Yes, it works in normal mode and returns no result in visual mode.

Below is my setup:
```

-- ntst = {noremap = true, silent = true},

translator = {
    {"n", "<leader>tsc", ":Translate ZH -output=split<cr>", "ntst"},
    {"x", "<leader>tsc", ":Translate ZH -output=split<cr>", "ntst"},
    {"n", "<leader>tse", ":Translate EN -output=split<cr>", "ntst"},
    {"x", "<leader>tse", ":Translate EN -output=split<cr>", "ntst"},
    {"n", "<leader>trc", ":Translate ZH -output=replace<cr>", "ntst"},
    {"x", "<leader>trc", ":Translate ZH -output=replace<cr>", "ntst"},
    {"n", "<leader>tre", ":Translate EN -output=replace<cr>", "ntst"},
    {"x", "<leader>tre", ":Translate EN -output=replace<cr>", "ntst"}
}
```

**Comment by uga-rosa** [comment]
Hmmm. I can't reproduce it.

Can you update to the latest version and plant `print(vim.inspect())` at the end of `L.get_visual_selected()` in `lua/translate/util/select.lua` to see what the variables are. `tl`, `br`, `lines`, `pos` I want to see.

**Comment by uga-rosa** [comment]
This is unrelated, but it is safer to use `:<C-u>` for normal mode mapping.

**Comment by askfiy** [comment]
> Hmmm. I can't reproduce it.
> 
> Can you update to the latest version and insert `print(vim.inspect())` at the end of `L.get_visual_selected()` in `lua/translate/util/select.lua` to see what the variables are? `tl`, `br`, `lines`, `pos` I want to see.


![image](https://user-images.githubusercontent.com/81478335/157604768-600db19d-26b1-4ee4-91be-728086ad638a.png)

**Comment by uga-rosa** [comment]
Hmmm. You're getting the range right.

**Comment by uga-rosa** [comment]
You got `text` right, too, right?

**Comment by uga-rosa** [comment]
Also, please show me the setup function. It's not the default, is it?

**Comment by askfiy** [comment]
> Hmmm. You're getting the range right. You got text right, too, right?

![image](https://user-images.githubusercontent.com/81478335/157605730-2a71f315-cc42-43cc-b2b0-9fe34c3fe6ce.png)

**Comment by askfiy** [comment]
>  Hmmm. You're getting the range right. You got text right, too, right?
> 
![image](https://user-images.githubusercontent.com/81478335/157605829-acf89f83-f7ca-496e-9adb-c138014785b0.png)

**Comment by askfiy** [comment]
> Also, please show me the setup function. It's not the default, is it?

![image](https://user-images.githubusercontent.com/81478335/157605931-d35b0f23-dbc3-4abd-b6ee-0a32076186f6.png)

**Comment by uga-rosa** [comment]
Wow. I wonder why it's working in my hand, does it only happen on V?

**Comment by askfiy** [comment]
> Wow. I wonder why it's working in my hand, does it only happen on `V`?

Yes, it won't work under both v and V .

**Comment by uga-rosa** [comment]
I see that mode is set to `n`. This seems to be the cause, but I don't know why it's happening.

**Comment by uga-rosa** [comment]
Please show me the result of `xmap <leader>tsc`

**Comment by askfiy** [comment]
> Please show me the result of `xmap <leader>tsc`

![image](https://user-images.githubusercontent.com/81478335/157606849-af390b66-e0ac-4d7b-b461-597687aa40cd.png)

**Comment by uga-rosa** [comment]
No problem there.
What is the version of neovim?

**Comment by askfiy** [comment]
> No problem there. What is the version of neovim?

![image](https://user-images.githubusercontent.com/81478335/157607137-bc49573f-2ff9-413b-9776-43850df2cfc6.png)

**Comment by askfiy** [comment]
> No problem there. What is the version of neovim?

![image](https://user-images.githubusercontent.com/81478335/157607193-5108c150-a29e-42de-bfc4-615f863bd578.png)

**Comment by uga-rosa** [comment]
I'm trying to get which visual mode it was by using the fact that when you hit a command from visual mode, the mode changes to V->n->c, but I guess this is not working.

**Comment by askfiy** [comment]
Please wait, I will close all other plugins to test if the plugin functions properly.

**Comment by askfiy** [comment]
Unfortunately, it is not affected by other plugins, the problem still exists.

**Comment by uga-rosa** [comment]
Do you do lazy loading? (If it works in other visual modes, it doesn't seem to matter.)

**Comment by askfiy** [comment]
> Do you do lazy loading? (If it works in other visual modes, it doesn't seem to matter.)

Yes, the conditions for lazy loading are:

```
cmd = "Translate"
```

**Comment by uga-rosa** [comment]
Oh, that's no good. Since we need to get the mode before executing the command.

**Comment by askfiy** [comment]
> Oh, that's no good. Since we need to get the mode before executing the command.

I tried to turn off lazy loading and this time a new problem appeared:

![image](https://user-images.githubusercontent.com/81478335/157609833-cde2f151-fbc1-4926-a4aa-5f01ae12efa5.png)

**Comment by askfiy** [comment]
> Oh, that's no good. Since we need to get the mode before executing the command.

It still doesn't work under v or V .

**Comment by uga-rosa** [comment]
Oh, 0.6.1 doesn't include ModeChanged events yet?

**Comment by askfiy** [comment]
> Oh, 0.6.1 doesn't include ModeChanged events yet?

I checked the manual and it was like this.

**Comment by uga-rosa** [comment]
I will look into how other plugins do it. Maybe I should change the mechanism.

**Comment by askfiy** [comment]
> I will look into how other plugins do it. Maybe I should change the mechanism.

Do you think this is the reason for the problem?

**Comment by uga-rosa** [comment]
Probably. My neovim has this event at master and I think that is the difference you and me.

**Comment by askfiy** [comment]
> Probably. My neovim has this event at master and I think that is the difference you and me.

I can try version 0.7 in a virtual machine to detect if this bug is caused by a version problem.

**Comment by uga-rosa** [comment]
Please do it.
Maybe I can solve it. is there `visualmode()` function in release?

**Comment by askfiy** [comment]
> Please do it. Maybe I can solve it. is there `visualmode()` function in release?

Yes, this exists in version 6.01.

**Comment by uga-rosa** [comment]
It seems to be available in 0.4, so it is rewritten to use this.

**Comment by uga-rosa** [comment]
Please update this plugin.

**Comment by askfiy** [comment]
Thanks a lot, it's working fine now.
