### ISSUE TITLE
How to set up British English for "deepl_free" and takeover the default rules of American English?

### ISSUE THREAD

**Issue by foersben** [uga-rosa/translate.nvim#30]
The curl command for deepl_free is based on https://www.deepl.com/en/docs-api/ and https://www.deepl.com/de/docs-api/translate-text:

```
curl -X POST 'https://api-free.deepl.com/v2/translate' \
	-H 'Authorization: DeepL-Auth-Key [yourAuthKey]' \
	-d 'text=Hallo%2C%20Welt!' \
	-d 'target_lang=EN_GB'
```

It probably goes somewhere into `args` according to the docs:
```
deepl_free ~

		table
		default: { args = {} }

		Set the extra arguments to be passed to the 'curl' command.
```

```
			require("translate").setup({
				default = {
					command = "deepl_free",
					output = "floating",
                                        args = "?",
				},
				preset = {
					output = {
						split = {
							append = true,
						},
					},
				},
			})
```

Where and how do I assign the other defaults of `EN` to `EN_GB`?

The mapping then should probably look as follows?:

```
			nnoremap ,t :<C-u>Translate EN_GB -output=floating<CR>
			vnoremap ,t :'<,'>Translate EN_GB -output=floating<CR>
```

I don't really know how to do it here. Thanks in advance!

**Comment by uga-rosa** [comment]
The target language for translation is always specified as an argument to the command. The format depends on the API, and since British English in deepl seems to be EN-GB, this is the way to go.

```vim
nnoremap ,t :<C-u>Translate EN-GB -output=floating<CR>
```

If the translation itself does not seem to work, check that `g:deepl_api_auth_key` is set correctly.
