### ISSUE TITLE
'floating' always shows extra ". " as prefix in the translated strings.

### ISSUE THREAD

**Issue by riodelphino** [uga-rosa/translate.nvim#32]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/translate.nvim/discussions).

### Description

Floating window always shows useless char ". " in front of the translated words.
So the end of the translated word is truncated and unreadable.

### Environments

MacOSX Ventura
neovim v0.10.0-dev-542+g19eef8156-dirty

### Minimal reproducible full config

```lua
require("translate").setup {
   default = {
      command = "google",
      output = "floating",
      parse_after = "head"
   }
}
```

### Steps to reproduce

1. Select the word "output" in visual mode.
2. `:Translate ja`

### Expected behavior

`出力` appears in floating window.

### Actual behavior

`. 出` appears in floating window.
The last char "力" was lost.
The extra ". " seems to hide the last char.

**Comment by uga-rosa** [comment]
Not reproducible.

![translate nvim](https://github.com/uga-rosa/translate.nvim/assets/82267684/49c26e49-fc1a-498f-85c4-b6b8638624d3)

Please recreate the minimum configuration that can be reproduced correctly.

**Comment by riodelphino** [comment]
Thank you for your quick reply !

As you guessed, I found out that the plugin 'marks.nvim' causes this problem.

It keeps '. ' as a sign of 'last modified line' in the signcolumn.
If I uninstall 'marks.nvim', the '. ' strings are disappeared from the floating window.

I want to use 'marks.nvim'.
And its config has a 'excluded_filetypes' option like below.

https://github.com/chentoast/marks.nvim
```lua
require'marks'.setup {
   -- Omit other settings
   excluded_filetypes = {},
}
```

But the translate's floating window doesn't seem to have the 'filetype' setting.


So I guess, adding this code

`api.nvim_buf_set_option(buf, 'filetype', 'translate')`

below this line
https://github.com/uga-rosa/translate.nvim/blob/35b71090a398eaca4d7cd2478f6a09d0fa3130bd/lua/translate/preset/output/floating.lua#L17C3-L17C50

might solve the problem.


Of course, I have to add the following setting in marks.nvim.

`excluded_filetypes = { "translate" },`


Thank you.

**Comment by uga-rosa** [comment]
Your proposal is compatible with `output/split`.
Now, the filetype `translate` is also set in `output/floating`.

**Comment by riodelphino** [comment]
Thank you !

Now it works !

<img width="120" alt="スクリーンショット 2023-08-04 21 26 54" src="https://github.com/uga-rosa/translate.nvim/assets/29378271/dde030b2-acd6-4ee9-8399-7e8c7c77e778">

With adding a new setting allowed by this change, like below.
```
require("translate").setup {
   preset = {
      output = {
         floating = {
            filetype = "translate",
         },
      },
   },
}
```

And also 
```
require'marks'.setup {
   excluded_filetypes = { "translate" },
}
```

**Comment by uga-rosa** [comment]
Sorry, I now added the default value.

**Comment by ZeparHyfar** [comment]
I had the same problem, but the above helped me solve it. 
Thank you!
