### ISSUE TITLE
word translation is not accurate

### ISSUE THREAD

**Issue by askfiy** [uga-rosa/translate.nvim#7]
Sometimes it is very common to translate a word, we will use viw to select a word.

But its translation result is not accurate. Also, you get some special symbols that have no real meaning.

In Chinese, `你好` should correspond to `Hello`, which is not accurate as you can see from the picture in v mode.

But in V mode, this is accurate.

![Peek 2022-03-14 20-33](https://user-images.githubusercontent.com/81478335/158172856-99978b93-4437-43e8-89d1-de757c5fbb50.gif)

**Comment by uga-rosa** [comment]
Oh, I'm sure that comes up from time to time too. I was going to investigate later.
I think the last byte is probably missing, since lua's string manipulation is basically one byte at a time.
Anyway, I'm going on a trip for a while starting tomorrow, so I'll be back for the rest of the story.

**Comment by askfiy** [comment]
That's great, have fun. Wear a mask when you go out, the epidemic is too scary now.

**Comment by uga-rosa** [comment]
Fixed on cc294cbc80497970a7065ce7c9bdc92a73645a6d
