### ISSUE TITLE
deepl_free url error due to lua closures

### ISSUE THREAD

**Issue by Cluas** [uga-rosa/translate.nvim#9]
https://github.com/uga-rosa/translate.nvim/blob/fefe3c27eda9be8bcea221b4dbcf9b80fcfcb4d3/lua/translate/config.lua#L13

Because `deepl_pro` was imported later, the url will eventually be replaced with `deepl_pro`'s, so `deepl_free` will not work properly.

**Comment by uga-rosa** [comment]
Thanks for reporting.
Please update to the latest version.

**Comment by Cluas** [comment]
I have forked and changed it similar to yours.😂 https://github.com/Cluas/translate.nvim/commit/a313101ec1a9ae2eab2e2c4eacb91bcb24c3a5ab

**Comment by uga-rosa** [comment]
I will do something about it when I have time. I don't like these mostly the same, wasteful codes too much!

**Comment by Cluas** [comment]
I found it yesterday when I was testing and I don't know much about it lua
